### ISSUE TITLE
Rep Track

### ISSUE THREAD

**Issue by gordsellar** [joesinghaus/Blades-in-the-Dark#6]
I seem to have discovered a problem with the Crew Sheet. 

For each piece of Turf the characters claim, their Rep Track is supposed to shorten. On the character sheet, this is represented by the right-side turf bars being filled in. (i.e. You fill in the Rep bars from the left for Rep taken through scores, but you also fill in the Rep track from the right for Claims.)

However, on the Crew sheet it seems that the Rep track only fills from left side. 

I'm not sure if it's feasible, but if the sheet automatically filled in some bars on the right side based on how much Turf the crew has, that'd be the best fix. Otherwise, maybe in the Edit Window giving an option to input a number (for items of Turf held) and then shortening the Rep track by that much would be a possible alternate approach. 

(Though it'd be good if the "removed" Rep bars remained visible, but colored something else—maybe all black—to remind players to adjust the number in the Edit window when a change occurs.)

Thanks! And thank you for the sheet, it's been a huge help in running games of BitD online!

**Comment by joesinghaus** [comment]
Hey @gordsellar! Sorry, took me a while to notice this. You can click the top half of one of the rep bars from the right in order to color them black and mark that they are covered by Turf (obviously this option is not accessible enough, but thoroughly explaining all the semi-hidden sheet mechanics is a bit of a larger project...). So I'm going to close this since it's already a function in the sheet.

**Comment by gordsellar** [comment]
Got it! Thanks!
